# NOMAD RSS Feeds Configuration
# This file contains RSS/Atom feeds for threat intelligence collection
# Priority levels: high (critical sources), medium (important), low (supplementary)
# Source types: cert, vendor, research, news, database

feeds:
  # === CERT/CSIRT/Government Advisory Feeds (Admiralty: A) ===
  - name: "CISA Cybersecurity Advisories"
    url: "https://www.cisa.gov/cybersecurity-advisories/all.xml"
    priority: high
    source_type: cert
    enabled: true
    check_frequency: hourly
    description: "US CISA advisories including ICS, medical, and general alerts"

  - name: "CISA Known Exploited Vulnerabilities"
    url: "https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json"
    priority: high
    source_type: cert
    enabled: true
    check_frequency: daily
    description: "CISA KEV catalog updates"

  - name: "US-CERT Current Activity"
    url: "https://www.cisa.gov/uscert/ncas/current-activity.xml"
    priority: high
    source_type: cert
    enabled: true
    check_frequency: hourly
    description: "US-CERT current activity alerts"

  - name: "NCSC UK Advisories"
    url: "https://www.ncsc.gov.uk/api/1/services/v1/all-rss-feed.xml"
    priority: high
    source_type: cert
    enabled: true
    check_frequency: daily
    description: "UK National Cyber Security Centre advisories"

  - name: "CERT-EU Latest News"
    url: "https://cert.europa.eu/cert/Data/newsletter/reviewlatest-rss.xml"
    priority: medium
    source_type: cert
    enabled: true
    check_frequency: daily
    description: "European Union CERT advisories"

  - name: "Canadian Centre for Cyber Security"
    url: "https://www.cyber.gc.ca/webservice/en/rss/alerts"
    priority: medium
    source_type: cert
    enabled: true
    check_frequency: daily
    description: "Canadian cyber security alerts"

  - name: "Australian Cyber Security Centre"
    url: "https://www.cyber.gov.au/rss.xml"
    priority: medium
    source_type: cert
    enabled: true
    check_frequency: daily
    description: "ACSC advisories and alerts"

  # === Major Vendor Security Advisories (Admiralty: A/B) ===
  - name: "Microsoft Security Response Center"
    url: "https://api.msrc.microsoft.com/update-guide/rss"
    priority: high
    source_type: vendor
    enabled: true
    check_frequency: hourly
    description: "Microsoft security updates and advisories"

  - name: "Microsoft Security Blog"
    url: "https://www.microsoft.com/en-us/security/blog/feed/"
    priority: medium
    source_type: vendor
    enabled: true
    check_frequency: daily
    description: "Microsoft security research and threat intelligence"

  - name: "Cisco Security Advisories"
    url: "https://sec.cloudapps.cisco.com/security/center/publicationService.x?i=100"
    priority: high
    source_type: vendor
    enabled: true
    check_frequency: daily
    description: "Cisco security advisories and responses"

  - name: "VMware Security Advisories"
    url: "https://www.vmware.com/security/advisories.xml"
    priority: high
    source_type: vendor
    enabled: true
    check_frequency: daily
    description: "VMware security updates"

  - name: "Oracle Critical Patch Updates"
    url: "https://www.oracle.com/technetwork/topics/security/alerts-086861.xml"
    priority: high
    source_type: vendor
    enabled: true
    check_frequency: daily
    description: "Oracle security patches and updates"

  - name: "Adobe Security Bulletins"
    url: "https://helpx.adobe.com/security.rss"
    priority: medium
    source_type: vendor
    enabled: true
    check_frequency: weekly
    description: "Adobe product security updates"

  - name: "Apple Security Updates"
    url: "https://support.apple.com/en-us/HT201222"
    priority: medium
    source_type: vendor
    enabled: true
    check_frequency: weekly
    description: "Apple security updates and patches"
    note: "May require HTML parsing"

  - name: "Google Chrome Releases"
    url: "https://chromereleases.googleblog.com/feeds/posts/default"
    priority: medium
    source_type: vendor
    enabled: true
    check_frequency: weekly
    description: "Chrome browser security updates"

  - name: "Mozilla Security Advisories"
    url: "https://www.mozilla.org/en-US/security/advisories/feed/"
    priority: medium
    source_type: vendor
    enabled: true
    check_frequency: weekly
    description: "Firefox and Mozilla product security"

  - name: "Red Hat Security Advisories"
    url: "https://access.redhat.com/blogs/product-security/feed"
    priority: high
    source_type: vendor
    enabled: true
    check_frequency: daily
    description: "RHEL and Red Hat product security"

  - name: "Ubuntu Security Notices"
    url: "https://ubuntu.com/security/notices/rss.xml"
    priority: medium
    source_type: vendor
    enabled: true
    check_frequency: daily
    description: "Ubuntu security updates"

  - name: "Fortinet Security Advisories"
    url: "https://www.fortiguard.com/rss/ir.xml"
    priority: high
    source_type: vendor
    enabled: true
    check_frequency: daily
    description: "FortiGate and Fortinet product security"

  - name: "Palo Alto Networks Security Advisories"
    url: "https://security.paloaltonetworks.com/rss.xml"
    priority: high
    source_type: vendor
    enabled: true
    check_frequency: daily
    description: "PAN-OS and Palo Alto security updates"

  - name: "Ivanti Security Updates"
    url: "https://forums.ivanti.com/s/feed/0D54O000090xgLWSAY"
    priority: high
    source_type: vendor
    enabled: true
    check_frequency: daily
    description: "Ivanti product security advisories"

  - name: "Citrix Security Bulletins"
    url: "https://support.citrix.com/feed/products/all/security-bulletins.xml"
    priority: high
    source_type: vendor
    enabled: true
    check_frequency: daily
    description: "Citrix product security updates"

  - name: "F5 Security Advisories"
    url: "https://support.f5.com/csp/rss/all-f5-security-advisories"
    priority: medium
    source_type: vendor
    enabled: true
    check_frequency: weekly
    description: "F5 BIG-IP and product security"

  - name: "SonicWall Security Advisories"
    url: "https://psirt.global.sonicwall.com/vuln-list/feed"
    priority: medium
    source_type: vendor
    enabled: true
    check_frequency: weekly
    description: "SonicWall firewall and security products"

  # === Security Research Organizations (Admiralty: B/C) ===
  - name: "Cisco Talos Intelligence"
    url: "https://blog.talosintelligence.com/feeds/posts/default"
    priority: medium
    source_type: research
    enabled: true
    check_frequency: daily
    description: "Cisco Talos threat research"

  - name: "Palo Alto Unit 42"
    url: "https://unit42.paloaltonetworks.com/feed/"
    priority: medium
    source_type: research
    enabled: true
    check_frequency: daily
    description: "Unit 42 threat research and analysis"

  - name: "CrowdStrike Intelligence"
    url: "https://www.crowdstrike.com/blog/feed/"
    priority: medium
    source_type: research
    enabled: true
    check_frequency: daily
    description: "CrowdStrike threat intelligence"

  - name: "Mandiant Threat Intelligence"
    url: "https://www.mandiant.com/resources/blog/rss.xml"
    priority: medium
    source_type: research
    enabled: true
    check_frequency: daily
    description: "Mandiant/FireEye threat research"

  - name: "Sophos Security News"
    url: "https://news.sophos.com/en-us/category/security-operations/feed/"
    priority: low
    source_type: research
    enabled: true
    check_frequency: daily
    description: "Sophos Labs threat research"

  - name: "Trend Micro Research"
    url: "https://blog.trendmicro.com/trendlabs-security-intelligence/feed/"
    priority: low
    source_type: research
    enabled: true
    check_frequency: daily
    description: "Trend Micro threat intelligence"

  - name: "Check Point Research"
    url: "https://research.checkpoint.com/feed/"
    priority: medium
    source_type: research
    enabled: true
    check_frequency: daily
    description: "Check Point security research"

  - name: "Qualys Security Blog"
    url: "https://blog.qualys.com/feed"
    priority: low
    source_type: research
    enabled: true
    check_frequency: weekly
    description: "Qualys vulnerability research"

  - name: "Rapid7 Blog"
    url: "https://blog.rapid7.com/rss/"
    priority: low
    source_type: research
    enabled: true
    check_frequency: weekly
    description: "Rapid7 security research and Metasploit"

  - name: "Tenable Research Advisories"
    url: "https://www.tenable.com/security/research/feed"
    priority: low
    source_type: research
    enabled: true
    check_frequency: weekly
    description: "Tenable vulnerability research"

  # === Vulnerability Databases (Admiralty: B) ===
  - name: "NVD Recent CVEs"
    url: "https://nvd.nist.gov/feeds/xml/cve/misc/nvd-rss.xml"
    priority: medium
    source_type: database
    enabled: true
    check_frequency: daily
    description: "NIST National Vulnerability Database updates"

  - name: "NVD Analyzed CVEs"
    url: "https://nvd.nist.gov/feeds/xml/cve/misc/nvd-rss-analyzed.xml"
    priority: medium
    source_type: database
    enabled: true
    check_frequency: daily
    description: "NVD recently analyzed CVEs"

  - name: "CVE Recent Updates"
    url: "https://cve.mitre.org/data/downloads/allitems.xml"
    priority: low
    source_type: database
    enabled: false
    check_frequency: daily
    description: "MITRE CVE database updates (large file)"

  - name: "VulnDB Recent Entries"
    url: "https://vuldb.com/?rss.recent"
    priority: low
    source_type: database
    enabled: true
    check_frequency: daily
    description: "VulnDB recent vulnerability entries"

  # === Security News and Media (Admiralty: C/D) ===
  - name: "BleepingComputer Security"
    url: "https://www.bleepingcomputer.com/feed/"
    priority: low
    source_type: news
    enabled: true
    check_frequency: daily
    description: "Security news and breach reporting"

  - name: "The Hacker News"
    url: "https://thehackernews.com/feeds/posts/default"
    priority: low
    source_type: news
    enabled: true
    check_frequency: daily
    description: "Cybersecurity news and updates"

  - name: "Dark Reading"
    url: "https://www.darkreading.com/rss.xml"
    priority: low
    source_type: news
    enabled: false
    check_frequency: daily
    description: "Enterprise security news"

  - name: "SecurityWeek"
    url: "https://feeds.feedburner.com/securityweek"
    priority: low
    source_type: news
    enabled: false
    check_frequency: daily
    description: "Security industry news"

# Configuration Settings
settings:
  # Maximum age of items to process (in days)
  max_item_age_days: 30

  # Deduplication window (in days)
  dedup_window_days: 7

  # Rate limiting between feed fetches (seconds)
  rate_limit_seconds: 2

  # User agent for feed fetching
  user_agent: "NOMAD-ThreatIntel/1.0 (+https://github.com/nomad-framework)"

  # Timeout for feed fetching (seconds)
  timeout_seconds: 30

  # Maximum items per feed to process
  max_items_per_feed: 100

  # Enable caching of feed data
  enable_cache: true
  cache_duration_hours: 1

# Feed Groups (for batch processing)
feed_groups:
  critical:
    description: "Critical feeds to check every hour"
    feeds:
      - "CISA Cybersecurity Advisories"
      - "CISA Known Exploited Vulnerabilities"
      - "US-CERT Current Activity"
      - "Microsoft Security Response Center"

  vendor_priority:
    description: "High-priority vendor feeds"
    feeds:
      - "Microsoft Security Response Center"
      - "Cisco Security Advisories"
      - "VMware Security Advisories"
      - "Oracle Critical Patch Updates"
      - "Red Hat Security Advisories"
      - "Fortinet Security Advisories"
      - "Palo Alto Networks Security Advisories"
      - "Ivanti Security Updates"
      - "Citrix Security Bulletins"

  research:
    description: "Security research organizations"
    feeds:
      - "Cisco Talos Intelligence"
      - "Palo Alto Unit 42"
      - "CrowdStrike Intelligence"
      - "Mandiant Threat Intelligence"
      - "Check Point Research"