# Claude Code Agent Configuration for NOMAD Framework
# This file maps NOMAD agents to Claude Code's agent types

agents:
  # Core Processing Agents
  rss_feed:
    name: "RSS Feed Agent"
    prompt_file: "rss-agent-prompt.md"
    subagent_type: "general-purpose"
    description: "Collects and normalizes threat intelligence from RSS feeds"
    input_required:
      - crawl_started_utc
      - feeds
      - since_utc
      - until_utc

  orchestrator:
    name: "Orchestrator Agent"
    prompt_file: "orchestrator-system-prompt.md"
    subagent_type: "general-purpose"
    description: "Routes intelligence items based on policy rules"
    input_required:
      - received_at_utc
      - items
      - context

  # Enhancement Agents
  enrichment:
    name: "Enrichment Agent"
    prompt_file: "enrichment-agent-prompt.md"
    subagent_type: "backend-architect"  # Good for API integrations
    description: "Enriches items with CVSS, EPSS, KEV data"
    input_required:
      - queried_at_utc
      - items

  dedup:
    name: "Deduplication Agent"
    prompt_file: "dedup-agent-prompt.md"
    subagent_type: "general-purpose"
    description: "Removes duplicate intelligence items"
    input_required:
      - items

  vendor_parser:
    name: "Vendor Parser Agent"
    prompt_file: "vendor-parser-agent-prompt.md"
    subagent_type: "general-purpose"
    description: "Parses vendor-specific security bulletins"
    input_required:
      - fetched_at_utc
      - advisory

  # Output Generation Agents
  technical_alert:
    name: "Technical Alert Generator"
    prompt_file: "technical-alert-prompt.md"
    subagent_type: "general-purpose"
    description: "Generates actionable SOC alerts"
    input_required:
      - routed_at_utc
      - route
      - item

  ciso_report:
    name: "CISO Report Generator"
    prompt_file: "ciso-report-generator-prompt.md"
    subagent_type: "general-purpose"
    description: "Creates executive-level summaries"
    input_required:
      - week_start
      - week_end
      - decisions

  watchlist_digest:
    name: "Watchlist Digest Agent"
    prompt_file: "watchlist-digest-agent-prompt.md"
    subagent_type: "general-purpose"
    description: "Summarizes watchlist items"
    input_required:
      - as_of_utc
      - watchlist

  evidence_vault:
    name: "Evidence Vault Writer"
    prompt_file: "evidence-vault-writer-prompt.md"
    subagent_type: "general-purpose"
    description: "Archives evidence with hashing"
    input_required:
      - items

# Workflow Definitions
workflows:
  # Morning security check workflow
  morning_check:
    name: "Morning Security Check"
    description: "Collect and process high-priority threats from last 24 hours"
    steps:
      - agent: rss_feed
        config:
          priority: high
          since: "24 hours ago"
      - agent: enrichment
      - agent: dedup
      - agent: orchestrator
      - conditional:
          - condition: "route == TECHNICAL_ALERT"
            agent: technical_alert
          - condition: "route == CISO_REPORT"
            agent: ciso_report

  # Weekly CISO report workflow
  weekly_report:
    name: "Weekly CISO Report"
    description: "Generate executive summary for the week"
    steps:
      - agent: rss_feed
        config:
          since: "7 days ago"
      - agent: enrichment
      - agent: orchestrator
      - agent: ciso_report

  # Vendor advisory check
  vendor_check:
    name: "Vendor Advisory Check"
    description: "Check specific vendor security bulletins"
    steps:
      - agent: rss_feed
        config:
          source_type: vendor
          priority: high
      - agent: vendor_parser
        optional: true
      - agent: enrichment
      - agent: orchestrator

  # Full pipeline
  full_pipeline:
    name: "Full NOMAD Pipeline"
    description: "Complete threat intelligence processing pipeline"
    steps:
      - agent: rss_feed
      - agent: enrichment
      - agent: dedup
      - agent: orchestrator
      - parallel:
          - agent: technical_alert
            condition: "route == TECHNICAL_ALERT"
          - agent: ciso_report
            condition: "route == CISO_REPORT"
          - agent: watchlist_digest
            condition: "route == WATCHLIST"
      - agent: evidence_vault

# Claude Code Agent Type Mappings
# Maps Claude Code's built-in agent types to their best use cases
agent_type_recommendations:
  general-purpose:
    description: "Best for most NOMAD agents - parsing, routing, generating"
    recommended_for:
      - rss_feed
      - orchestrator
      - dedup
      - technical_alert
      - ciso_report

  backend-architect:
    description: "Best for API integrations and data enrichment"
    recommended_for:
      - enrichment
      - vendor_parser

  python-expert:
    description: "Best for implementing custom logic or data processing"
    recommended_for:
      - custom_analytics
      - data_transformation

  qa-evaluator:
    description: "Best for validating agent outputs and quality checks"
    recommended_for:
      - output_validation
      - schema_checking

  workflow-optimizer:
    description: "Best for optimizing the overall pipeline"
    recommended_for:
      - pipeline_optimization
      - performance_tuning

# Execution Settings
settings:
  # Default timeout for agent execution (seconds)
  agent_timeout: 300

  # Whether to save intermediate outputs
  save_intermediate: true

  # Output directory for agent results
  output_dir: "data/output"

  # Input directory for agent inputs
  input_dir: "data/input"

  # Cache directory
  cache_dir: "data/cache"

  # Enable verbose logging
  verbose: true

  # Maximum retries for failed agents
  max_retries: 2

  # Default date range for RSS collection
  default_lookback_days: 7